# This is a basic workflow to help you get started with Actions

name: GHA inputs test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      appname:
        description: "The application name"
        required: true
        default: "sample app"
      apptype:
        description: "The application type"
        required: true
        default: "webapp"
        type: choice
        options:
          - mobile
          - webapp
          - both
      environment:
        description: "The deployment environment"
        required: true
        type: environment
      notify:
        description: "Notify deployment"
        required: true
        type: boolean
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "Deploying app ${{ github.event.inputs.appname }} to ${{ github.event.inputs.environment }} environment"
